server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/jobSeeking"
    username: root
    password: 123456
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: api
    password: 34bb364b211bf52780c5e9ed4155b779
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
      default_schema: public
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
jwt:
  signerKey: "LHdv9EVi3BKZeBHVBzqPE35+0PzgIPPlEkDa+8WSugOj+QAXKDO3DfjPDhSYmkjN"
